# Generated by Django 6.0.3 on 2026-04-04 08:24

from django.db import migrations, models


def dedupe_user_emails(apps, schema_editor):
    _ = schema_editor
    User = apps.get_model("users", "User")

    seen = set()
    for user in User.objects.order_by("id").iterator():
        email = (user.email or "").strip().lower()

        if not email:
            email = f"user{user.id}@placeholder.local"

        local_part, sep, domain = email.partition("@")
        if not sep:
            local_part = f"user{user.id}"
            domain = "placeholder.local"

        candidate = f"{local_part}@{domain}"
        suffix = 2
        while candidate in seen:
            candidate = f"{local_part}+dup{suffix}@{domain}"
            suffix += 1

        user.email = candidate
        user.save(update_fields=["email"])
        seen.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(dedupe_user_emails, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
