# Generated by Django 6.0.3 on 2026-04-04 08:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
        ('tickets', '0001_initial'),
        ('trips', '0002_trip_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_trip_seat_ticket',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'BOOKED')), fields=('trip', 'seat'), name='unique_trip_seat_ticket'),
        ),
    ]
