# Generated by Django 6.0.3 on 2026-04-18 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
        ('tickets', '0003_initial'),
        ('trips', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_trip_seat_ticket',
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='ETB', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('CHAPA', 'Chapa')], default='CHAPA', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled'), ('USED', 'Used')], default='RESERVED', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['RESERVED', 'BOOKED'])), fields=('trip', 'seat'), name='unique_trip_seat_ticket'),
        ),
    ]