# Generated by Django 6.0.3 on 2026-04-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticket_unique_trip_seat_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fare_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]