# Generated by Django 6.0.3 on 2026-04-04 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0001_initial'),
        ('routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='buses.bus')),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'DRIVER'}, on_delete=django.db.models.deletion.PROTECT, related_name='driven_trips', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='routes.route')),
            ],
            options={
                'ordering': ['-departure_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('arrival_time__gt', models.F('departure_time'))), name='trip_arrival_after_departure')],
            },
        ),
    ]
