# Generated by Django 6.0.3 on 2026-04-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="fare",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
